# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# executors:
#   exec1:
#     docker:
#       – image: debian:stable-slim

# workflows
workflows:
  main:
    jobs:
      - buildAndTest

# list of possible jobs and steps
jobs:
  buildAndTest:
    # executor: exec1
    docker:
      - image: debian:bullseye-slim
    steps:
      - run:
          name: Installing dependencies
          command: |
            apt-get update
            apt-get install -y sudo build-essential cmake git ninja-build libnetcdf-dev libglew-dev libglu1-mesa-dev xorg-dev libasound2-dev python3 python3-pip python3-protobuf python3-netcdf4 lcov curl
            rm -rf /var/lib/apt/lists/*
            pip install coverage tinc
      - checkout
      - run:
          name: Checkout submodules
          command: git submodule update --recursive --init
      - run:
          name: Cmake config
          command: |
            mkdir -p build
            cd build
            cmake .. -DTINC_BUILD_TESTS=ON -DTINC_CODE_COVERAGE=ON
      - run:
          name: Cmake build
          command: |
            cd build
            cmake --build . -j7
      - run:
          name: Run Cpp tests
          command: ./bin/tinc_tests
      - run:
          name: Run Python tests
          command: cd tinc-python/tinc/tests; coverage run ./unit_tests.py ; coverage report -m
      - run:
          name: Code coverage report
          command: |
            for filename in `find src/. | egrep '\.cpp'`;
            do
              gcov -n -o . $filename > /dev/null;
            done
            # Create lcov report
            lcov --capture --directory . --output-file coverage.info
            lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter system-files
            lcov --list coverage.info # debug info
            # Uploading report to CodeCov
            bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

